[project]
name = "Leisungskurve_II"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "bl2615mci",email = "bl2615@mci4me.at"},
]
dependencies = ["pandas>=3.0.3", "matplotlib>=3.10.9", "plotly>=6.8.0", "kaleido"]
requires-python = ">3.12"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
